// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooApp.WebAPI.Data;

#nullable disable

namespace ZooApp.WebAPI.Migrations
{
    [DbContext(typeof(ZooContext))]
    [Migration("20240807222716_AddDataModelCreate")]
    partial class AddDataModelCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.AnimalModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoundFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoundUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeSound")
                        .HasColumnType("TEXT");

                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZooModelID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("ZooModelID");

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.GuestModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ZooModelID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.HasIndex("ZooModelID");

                    b.ToTable("Guests", (string)null);
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.ZooModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("UUID")
                        .IsUnique();

                    b.ToTable("Zoos", (string)null);
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.AnimalModel", b =>
                {
                    b.HasOne("ZooApp.WebAPI.Data.Model.ZooModel", null)
                        .WithMany("Animals")
                        .HasForeignKey("ZooModelID");
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.GuestModel", b =>
                {
                    b.HasOne("ZooApp.WebAPI.Data.Model.ZooModel", null)
                        .WithMany("Guests")
                        .HasForeignKey("ZooModelID");
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.ZooModel", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
