// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZooApp.WebAPI.Data;

#nullable disable

namespace ZooApp.WebAPI.Migrations
{
    [DbContext(typeof(ZooContext))]
    partial class ZooContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.AnimalModel", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SoundFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("SoundUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Species")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeSound")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZooUUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("ZooUUID");

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.GuestModel", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZooUUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("ZooUUID");

                    b.ToTable("Guests", (string)null);
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.ZooModel", b =>
                {
                    b.Property<string>("UUID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UUID");

                    b.ToTable("Zoos", (string)null);
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.AnimalModel", b =>
                {
                    b.HasOne("ZooApp.WebAPI.Data.Model.ZooModel", "Zoo")
                        .WithMany("Animals")
                        .HasForeignKey("ZooUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.GuestModel", b =>
                {
                    b.HasOne("ZooApp.WebAPI.Data.Model.ZooModel", "Zoo")
                        .WithMany("Guests")
                        .HasForeignKey("ZooUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zoo");
                });

            modelBuilder.Entity("ZooApp.WebAPI.Data.Model.ZooModel", b =>
                {
                    b.Navigation("Animals");

                    b.Navigation("Guests");
                });
#pragma warning restore 612, 618
        }
    }
}
